model:
  use_sta: true
  use_sta_bias: true
  sta:
    k_mirror: 8
    beta: 1.5
    temperature: 0.07
loss_weights:
  w_cd: 1.0
  w_emd: 0.0
  w_symp: 0.1
  w_symg: 0.1
train:
  schedule: e2e
  sta_ramp_epochs: 10
logging:
  log_sta_params: true
  level: INFO